<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>JapaneseOfflineClientRequestDiagnostics</AssemblyName>
    <RootNamespace>JapaneseOfflineClientRequestDiagnostics</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="BepInEx.Core">
      <HintPath>$(JapaneseRoot)\BepInEx\core\BepInEx.Core.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Unity.IL2CPP">
      <HintPath>$(JapaneseRoot)\BepInEx\core\BepInEx.Unity.IL2CPP.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>$(JapaneseRoot)\BepInEx\core\Il2CppInterop.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(JapaneseRoot)\BepInEx\core\0Harmony.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
