<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>JapaneseOfflineProxy</AssemblyName>
    <RootNamespace>JapaneseOfflineProxy</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="BepInEx.Core">
      <HintPath>$(JapaneseRoot)\BepInEx\core\BepInEx.Core.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Unity.IL2CPP">
      <HintPath>$(JapaneseRoot)\BepInEx\core\BepInEx.Unity.IL2CPP.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(JapaneseRoot)\BepInEx\core\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>$(JapaneseRoot)\BepInEx\core\Il2CppInterop.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="BestHTTP">
      <HintPath>$(JapaneseRoot)\BepInEx\interop\BestHTTP.dll</HintPath>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>$(JapaneseRoot)\BepInEx\interop\Il2Cppmscorlib.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSystem">
      <HintPath>$(JapaneseRoot)\BepInEx\interop\Il2CppSystem.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(JapaneseRoot)\BepInEx\unity-libs\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>$(JapaneseRoot)\BepInEx\unity-libs\UnityEngine.UnityWebRequestModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
